version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
            export PATH=$HOME/.yarn/bin:$PATH
      - run: yarn install --offline --frozen-lockfile
      - run:
          name: Run ci checks
          command: yarn ci-check
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
            export PATH=$HOME/.yarn/bin:$PATH
      - run:
          name: Publish carbon-upgrade
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_USER

              yarn publish --new-version $CIRCLE_TAG
              git push origin master --tags
            fi

workflows:
  version: 2
  main:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
